-- Internal link suggestions generated by the linking engine
CREATE TABLE IF NOT EXISTS link_suggestions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  site_id UUID NOT NULL REFERENCES sites(id) ON DELETE CASCADE,

  -- The page that should contain the new link
  source_page_id UUID NOT NULL REFERENCES pages(id) ON DELETE CASCADE,

  -- The page being linked to
  target_page_id UUID NOT NULL REFERENCES pages(id) ON DELETE CASCADE,

  -- Suggested anchor text
  anchor_text TEXT NOT NULL,

  -- Where in the source page to insert (paragraph index or context snippet)
  context_snippet TEXT,                  -- surrounding text where the link fits

  -- Scoring
  similarity_score FLOAT,               -- cosine similarity (0-1)
  relevance_score FLOAT,                -- adjusted score considering content types
  confidence TEXT DEFAULT 'medium',      -- low | medium | high

  -- Approval workflow
  status TEXT DEFAULT 'pending',         -- pending | approved | rejected | applied
  reviewed_at TIMESTAMPTZ,
  reviewed_by TEXT,                      -- who approved/rejected
  applied_at TIMESTAMPTZ,

  -- Reason for suggestion
  reason TEXT,                           -- "semantically similar", "orphan page rescue", etc.

  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_suggestions_site ON link_suggestions (site_id);
CREATE INDEX idx_suggestions_status ON link_suggestions (status);
CREATE INDEX idx_suggestions_source ON link_suggestions (source_page_id);
CREATE INDEX idx_suggestions_target ON link_suggestions (target_page_id);

-- Prevent duplicate suggestions
CREATE UNIQUE INDEX idx_suggestions_unique
  ON link_suggestions (source_page_id, target_page_id)
  WHERE status != 'rejected';
